// 'use client'

// import './globals.css'
// import { Inter } from 'next/font/google'
// import { createPagesBrowserClient } from '@supabase/auth-helpers-nextjs'
// import {SessionContextProvider} from '@supabase/auth-helpers-react'
// import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   const [supabaseClient] = useState(() => createPagesBrowserClient());
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//     <SessionContextProvider
//         supabaseClient={supabaseClient}>
//     </SessionContextProvider>
//   )
// }

'use client'

import { createPagesBrowserClient } from '@supabase/auth-helpers-nextjs'
import { SessionContextProvider } from '@supabase/auth-helpers-react'
import { useState } from 'react'

function RootLayout({ Component, pageProps }) {
  // Create a new supabase browser client on every first render.
  const [supabaseClient] = useState(() => createPagesBrowserClient())

  return (
    <SessionContextProvider
      supabaseClient={supabaseClient}
      initialSession={pageProps.initialSession}
    >
      <Component {...pageProps} />
    </SessionContextProvider>
  )
}